name: Terraform Deployment

# Trigger this workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Change to the required Terraform version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform code (optional)
      - name: Terraform Validate
        run: terraform validate

      # Plan the changes
      - name: Terraform Plan
        run: terraform plan

      # Apply the changes (optional - use auto-apply cautiously)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      # Optional: Slack notification, etc.
      # You can send notifications here using Slack or other services
