name: GCP Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure to GCP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate with GCP using the service account key stored in the secret
      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Update this to match your version

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan (pass variables explicitly)
      - name: Terraform Plan
        run: terraform plan \
          -var "billing_id=${{ secrets.billing_id }}" \
          -var "project_id=${{ secrets.project_id }}" \
          -var "org_id=''" \
          -var "folder_id=''"

      # Step 6: Terraform Apply (deploy changes automatically, be cautious)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
