name: GCP Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure to GCP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to get the Terraform files
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud using service account credentials
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Setup gcloud SDK (optional, only if gcloud commands are needed)
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      # Step 4: Setup Terraform (installs Terraform CLI)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Specify your desired Terraform version

      # Step 5: Initialize Terraform (downloads modules, plugins, and sets up backend)
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Plan (preview the changes to be applied)
      - name: Terraform Plan
        run: |
          terraform plan \
            -var "billing_id=${{ secrets.BILLING_ID }}" \
            -var "project_id=${{ secrets.PROJECT_ID }}" \
            -var "org_id='Self'" \
            -var "folder_id=''"
      
      # Step 7: Terraform Apply (apply changes to GCP infrastructure)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          terraform apply \
            -var "billing_id=${{ secrets.BILLING_ID }}" \
            -var "project_id=${{ secrets.PROJECT_ID }}" \
            -var "org_id='Self'" \
            -var "folder_id=''" \
            -auto-approve
